package com.github.jts.tasks.imlps;

import com.github.jts.executor.Executor;
import com.github.jts.scheuduler.ConditionalScheduler;
import com.github.jts.scheuduler.Scheduler;
import com.github.jts.tasks.AbstractTask;
import com.github.jts.tasks.TaskAction;
import com.github.jts.tasks.TaskConfig;
import com.github.jts.tasks.TaskListener;
import com.github.jts.tasks.builders.ConditionalTaskBuilder;
import com.github.jts.time.InvalidTimeException;
import com.github.jts.time.Time;
import com.github.jts.timer.Timer;
import com.github.utilities.validators.Preconditions;

import java.util.List;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.function.BooleanSupplier;


/**
 * An {@code conditional task} is an {@code iterative task} that specify a condition via
 * the {@link #getCondition()} property that is a {@link BooleanSupplier}. The task will
 * only execute if the condition returns {@code true}.
 */
public class ConditionalTask extends AbstractTask {
    private final Scheduler scheduler;
    private final BooleanSupplier condition;

    public ConditionalTask(String id, Executor executor, Timer timer, Time initialDelay, TaskConfig config,
                           List<TaskListener> listeners, BooleanSupplier condition, TaskAction action) {
        super(id, executor, timer, initialDelay, config, listeners, action);
        this.scheduler = new ConditionalScheduler(this);
        this.condition = Preconditions.simpleParameterNotNull(condition, "condition");
    }

    public ConditionalTask(String id, Executor executor, Timer timer, Time initialDelay, TaskConfig config,
                           BooleanSupplier condition, TaskAction action) {
        super(id, executor, timer, initialDelay, config, new CopyOnWriteArrayList<>(), action);
        this.scheduler = new ConditionalScheduler(this);
        this.condition = Preconditions.simpleParameterNotNull(condition, "condition");
    }

    /**
     * Creates a new synchronized instance of {@link IntervalTask} with the given parameters.
     *
     * @param id        the identifier of the task; Autogenerated if null or empty.
     * @param initDelay the initial delay of the task.
     * @param condition the condition of the {@link IntervalTask}
     * @param config    the configuration of this task.
     * @param action    The action to that the task execute.
     * @return a new {@link IntervalTask}; not-null.
     * @throws InvalidTimeException If the time is invalid.
     * @throws NullPointerException If the one of action or the interval is null.
     */
    public static ConditionalTask sync(String id, Time initDelay, TaskConfig config, BooleanSupplier condition, TaskAction action) {
        return builder()
                .withID(id)
                .withInitialDelay(initDelay)
                .withConfig(config)
                .withCondition(condition)
                .withAction(action)
                .synchronous()
                .build();
    }

    /**
     * Creates a new synchronized instance of {@link IntervalTask} with the given parameters.
     *
     * @param id        the identifier of the task; Autogenerated if null or empty.
     * @param initDelay the initial delay of the task.
     * @param condition the condition of the {@link IntervalTask}
     * @param action    the action to that the task execute.
     * @return a new {@link IntervalTask}; not-null.
     * @throws InvalidTimeException If the time is invalid.
     * @throws NullPointerException If the one of action or the interval is null.
     */
    public static ConditionalTask sync(String id, Time initDelay, BooleanSupplier condition, TaskAction action) {
        return builder()
                .withID(id)
                .withInitialDelay(initDelay)
                .withCondition(condition)
                .withAction(action)
                .synchronous()
                .build();
    }

    /**
     * Creates a new synchronized instance of {@link IntervalTask} with the given parameters.
     *
     * @param id        the identifier of the task; Autogenerated if null or empty.
     * @param condition the condition of the {@link IntervalTask}
     * @param action    the action to that the task execute.
     * @return a new {@link IntervalTask}; not-null.
     * @throws NullPointerException If the one of action or the interval is null.
     */
    public static ConditionalTask sync(String id, BooleanSupplier condition, TaskAction action) {
        return builder()
                .withID(id)
                .withCondition(condition)
                .withAction(action)
                .synchronous()
                .build();
    }

    /**
     * Creates a new synchronized instance of {@link IntervalTask} with the given parameters.
     *
     * @param condition the condition of the {@link IntervalTask}
     * @param action    the action to that the task execute.
     * @return a new {@link IntervalTask}; not-null.
     * @throws NullPointerException If the one of action or the interval is null.
     */
    public static ConditionalTask sync(BooleanSupplier condition, TaskAction action) {
        return builder()
                .withCondition(condition)
                .withAction(action)
                .synchronous()
                .build();
    }

    /**
     * Creates a new asynchronized instance of {@link IntervalTask} with the given parameters.
     *
     * @param id        the identifier of the task; Autogenerated if null or empty.
     * @param initDelay the initial delay of the task.
     * @param condition the condition of the {@link IntervalTask}
     * @param config    the configuration of this task.
     * @param action    The action to that the task execute.
     * @return a new {@link IntervalTask}; not-null.
     * @throws InvalidTimeException If the time is invalid.
     * @throws NullPointerException If the one of action or the interval is null.
     */
    public static ConditionalTask async(String id, Time initDelay, TaskConfig config, BooleanSupplier condition, TaskAction action) {
        return builder()
                .withID(id)
                .withInitialDelay(initDelay)
                .withConfig(config)
                .withCondition(condition)
                .withAction(action)
                .asynchronous()
                .build();
    }

    /**
     * Creates a new asynchronized instance of {@link IntervalTask} with the given parameters.
     *
     * @param id        the identifier of the task; Autogenerated if null or empty.
     * @param initDelay the initial delay of the task.
     * @param condition the condition of the {@link IntervalTask}
     * @param action    the action to that the task execute.
     * @return a new {@link IntervalTask}; not-null.
     * @throws InvalidTimeException If the time is invalid.
     * @throws NullPointerException If the one of action or the interval is null.
     */
    public static ConditionalTask async(String id, Time initDelay, BooleanSupplier condition, TaskAction action) {
        return builder()
                .withID(id)
                .withInitialDelay(initDelay)
                .withCondition(condition)
                .withAction(action)
                .asynchronous()
                .build();
    }

    /**
     * Creates a new asynchronized instance of {@link IntervalTask} with the given parameters.
     *
     * @param id        the identifier of the task; Autogenerated if null or empty.
     * @param condition the condition of the {@link IntervalTask}
     * @param action    the action to that the task execute.
     * @return a new {@link IntervalTask}; not-null.
     * @throws NullPointerException If the one of action or the interval is null.
     */
    public static ConditionalTask async(String id, BooleanSupplier condition, TaskAction action) {
        return builder()
                .withID(id)
                .withCondition(condition)
                .withAction(action)
                .asynchronous()
                .build();
    }

    /**
     * Creates a new asynchronized instance of {@link IntervalTask} with the given parameters.
     *
     * @param condition the condition of the {@link IntervalTask}
     * @param action    the action to that the task execute.
     * @return a new {@link IntervalTask}; not-null.
     * @throws NullPointerException If the one of action or the interval is null.
     */
    public static ConditionalTask async(BooleanSupplier condition, TaskAction action) {
        return builder()
                .withCondition(condition)
                .withAction(action)
                .asynchronous()
                .build();
    }

    /**
     * Retrieves a new builder for a {@link IntervalTask}
     *
     * @return a builder for a {@link IntervalTask}.
     */
    private static ConditionalTaskBuilder builder() {
        return new ConditionalTaskBuilder();
    }

    public BooleanSupplier getCondition() {
        return condition;
    }

    @Override
    public Scheduler getScheduler() {
        return scheduler;
    }
}
