package com.github.jts.tasks.imlps;

import com.github.jts.executor.Executor;
import com.github.jts.scheuduler.Scheduler;
import com.github.jts.scheuduler.IntervalScheduler;
import com.github.jts.tasks.AbstractTask;
import com.github.jts.tasks.TaskAction;
import com.github.jts.tasks.TaskConfig;
import com.github.jts.tasks.TaskListener;
import com.github.jts.tasks.builders.IntervalTaskBuilder;
import com.github.jts.time.InvalidTimeException;
import com.github.jts.time.Time;
import com.github.jts.timer.Timer;

import java.util.List;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.concurrent.atomic.AtomicLong;

/**
 * An {@code interval task} is an {@code iterative task} that specify an amount of time
 * between each execution. This time that must elapse between executions is defined by the
 * {@link #getInterval()} property.
 */
public class IntervalTask extends AbstractTask {
    private final Scheduler scheduler;
    private final Time interval;
    private final AtomicLong lastExecutionTime = new AtomicLong(0);

    public IntervalTask(String id, Executor executor, Timer timer,
                        Time initialDelay, Time interval, TaskConfig config,
                        List<TaskListener> listeners, TaskAction action) {
        super(id, executor, timer, initialDelay, config, action);

        this.interval = Time.ensure(interval);
        this.scheduler = new IntervalScheduler(this);
        setAction(() -> {
            action.execute();
            lastExecutionTime.set(System.currentTimeMillis());
        });
    }

    public IntervalTask(String id, Executor executor, Timer timer,
                        Time initialDelay, Time interval, TaskConfig config,
                        TaskAction action) {
        this(id, executor, timer, initialDelay, interval, config, new CopyOnWriteArrayList<>(), action);
    }


    /**
     * Creates a new synchronized instance of {@link IntervalTask} with the given parameters.
     *
     * @param id        the identifier of the task; Autogenerated if null or empty.
     * @param initDelay the initial delay of the task.
     * @param interval  the interval of the {@link IntervalTask}
     * @param config    the configuration of this task.
     * @param action    The action to that the task execute.
     * @return a new {@link IntervalTask}; not-null.
     * @throws InvalidTimeException If the time is invalid.
     * @throws NullPointerException If the one of action or the interval is null.
     */
    public static IntervalTask sync(String id, Time initDelay, Time interval, TaskConfig config, TaskAction action) {
        return builder()
                .withID(id)
                .withInitialDelay(initDelay)
                .withConfig(config)
                .withInterval(interval)
                .withAction(action)
                .synchronous()
                .build();
    }

    /**
     * Creates a new synchronized instance of {@link IntervalTask} with the given parameters.
     *
     * @param id        the identifier of the task; Autogenerated if null or empty.
     * @param initDelay the initial delay of the task.
     * @param interval  the interval of the {@link IntervalTask}
     * @param action    the action to that the task execute.
     * @return a new {@link IntervalTask}; not-null.
     * @throws InvalidTimeException If the time is invalid.
     * @throws NullPointerException If the one of action or the interval is null.
     */
    public static IntervalTask sync(String id, Time initDelay, Time interval, TaskAction action) {
        return builder()
                .withID(id)
                .withInitialDelay(initDelay)
                .withInterval(interval)
                .withAction(action)
                .synchronous()
                .build();
    }

    /**
     * Creates a new synchronized instance of {@link IntervalTask} with the given parameters.
     *
     * @param id       the identifier of the task; Autogenerated if null or empty.
     * @param interval the interval of the {@link IntervalTask}
     * @param action   the action to that the task execute.
     * @return a new {@link IntervalTask}; not-null.
     * @throws InvalidTimeException If the time is invalid.
     * @throws NullPointerException If the one of action or the interval is null.
     */
    public static IntervalTask sync(String id, Time interval, TaskAction action) {
        return builder()
                .withID(id)
                .withInterval(interval)
                .withAction(action)
                .synchronous()
                .build();
    }

    /**
     * Creates a new synchronized instance of {@link IntervalTask} with the given parameters.
     *
     * @param interval the interval of the {@link IntervalTask}
     * @param action   the action to that the task execute.
     * @return a new {@link IntervalTask}; not-null.
     * @throws InvalidTimeException If the time is invalid.
     * @throws NullPointerException If the one of action or the interval is null.
     */
    public static IntervalTask sync(Time interval, TaskAction action) {
        return builder()
                .withInterval(interval)
                .withAction(action)
                .synchronous()
                .build();
    }


    /**
     * Creates a new asynchronized instance of {@link IntervalTask} with the given parameters.
     *
     * @param id        the identifier of the task; Autogenerated if null or empty.
     * @param initDelay the initial delay of the task.
     * @param interval  the interval of the {@link IntervalTask}
     * @param config    the configuration of this task.
     * @param action    The action to that the task execute.
     * @return a new {@link IntervalTask}; not-null.
     * @throws InvalidTimeException If the time is invalid.
     * @throws NullPointerException If the one of action or the interval is null.
     */
    public static IntervalTask async(String id, Time initDelay, Time interval, TaskConfig config, TaskAction action) {
        return builder()
                .withID(id)
                .withInitialDelay(initDelay)
                .withConfig(config)
                .withInterval(interval)
                .withAction(action)
                .asynchronous()
                .build();
    }

    /**
     * Creates a new asynchronized instance of {@link IntervalTask} with the given parameters.
     *
     * @param id        the identifier of the task; Autogenerated if null or empty.
     * @param initDelay the initial delay of the task.
     * @param interval  the interval of the {@link IntervalTask}
     * @param action    the action to that the task execute.
     * @return a new {@link IntervalTask}; not-null.
     * @throws InvalidTimeException If the time is invalid.
     * @throws NullPointerException If the one of action or the interval is null.
     */
    public static IntervalTask async(String id, Time initDelay, Time interval, TaskAction action) {
        return builder()
                .withID(id)
                .withInitialDelay(initDelay)
                .withInterval(interval)
                .withAction(action)
                .asynchronous()
                .build();
    }


    /**
     * Creates a new asynchronized instance of {@link IntervalTask} with the given parameters.
     *
     * @param id       the identifier of the task; Autogenerated if null or empty.
     * @param interval the interval of the {@link IntervalTask}
     * @param action   the action to that the task execute.
     * @return a new {@link IntervalTask}; not-null.
     * @throws InvalidTimeException If the time is invalid.
     * @throws NullPointerException If the one of action or the interval is null.
     */
    public static IntervalTask async(String id, Time interval, TaskAction action) {
        return builder()
                .withID(id)
                .withInterval(interval)
                .withAction(action)
                .asynchronous()
                .build();
    }

    /**
     * Creates a new asynchronized instance of {@link IntervalTask} with the given parameters.
     *
     * @param interval the interval of the {@link IntervalTask}
     * @param action   the action to that the task execute.
     * @return a new {@link IntervalTask}; not-null.
     * @throws InvalidTimeException If the time is invalid.
     * @throws NullPointerException If the one of action or the interval is null.
     */
    public static IntervalTask async(Time interval, TaskAction action) {
        return builder()
                .withInterval(interval)
                .withAction(action)
                .asynchronous()
                .build();
    }

    /**
     * Retrieves a new builder for a {@link IntervalTask}
     *
     * @return a builder for a {@link IntervalTask}.
     */
    private static IntervalTaskBuilder builder() {
        return new IntervalTaskBuilder();
    }

    /**
     * Retrieves the last time that this task has been executed in milliseconds.
     *
     * @return The last execution time in milliseconds.
     */
    public long getLastTimeExecuted() {
        return lastExecutionTime.get();
    }

    /**
     * Retrieves the interval to wait between each execution of this task.
     *
     * @return The interval between executions.
     */
    public Time getInterval() {
        return interval;
    }

    @Override
    public Scheduler getScheduler() {
        return scheduler;
    }
}
